baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Mark Poko'
theme = "risotto"

# Automatically add content sections to main menu
sectionPagesMenu = "main"

# Sidebar: about/bio
[params.about]
title = "risotto"
description = "A [hugo](https://gohugo.io) theme inspired by terminal ricing."
logo = "images/rice.svg"


[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/pokom/pokom"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"